CREATE TABLE Products(
id INT PRIMARY KEY NOT NULL,
Number INT NOT NULL UNIQUE,
Brands VARCHAR(45) NOT NULL,
Model VARCHAR(45) NOT NULL,
Description VARCHAR(45) NOT NULL,
Prices FLOAT NOT NULL,
Nb_pieces INT NOT NULL
);